import React from 'react';
import { Row, Col } from 'react-bootstrap'
import './learn.css'

const LearnPage = () => {
  return (
    <div>
      <Row className='learn-content'>
        <Col lg={3}></Col>

        <Col lg={6} className='px-3'>
          <h4>THE BIG PICTURE</h4>
          <h5>(Membership, Marketplace, Community wallet, DAO)</h5>
          <ul>
            <li><u><h5>Project Noise Collectors Club</h5></u></li>
          </ul>
          <p>
            Each noise owned will double up as a membership pass for the Project Noise collectors club. By being in this club, you will have early minting access to all future collections. The premium collections will solely be reserved for the club members while others will be made public after a members-only pre-sale is concluded.<br />
            We aim to bring the community of art collectors together on the Solana blockchain and offer them hand-picked curations of the most exquisite artworks available.
          </p>
          <ul>
            <li><u><h5>Generative Art Marketplace</h5></u></li>
          </ul>
          <p>
            We will be launching a generative art marketplace, thus providing the rising talents to host their works.
          </p>
          <ul>
            <li><u><h5>Community Wallet and DAO</h5></u></li>
          </ul>
          <p>
            A community wallet is set up where-in a certain percentage of all initial sales will continue to accrue over time. As for the first series (REF1ECT), 15% of the initial sale will go into this wallet. This capital will be used to support the NFT space on Solana by purchasing new and upcoming projects.
            <br />
            <br />
            A DAO will be set up to vote on these purchases and for a fractionalized ownership of its assets among all the members.
          </p>

          <div className='division-div'></div>

          <h4 className='subheading'>The Creation Process</h4>
          <p>
            All 2,222 artworks in this series are randomly generated by tweaking one mother script. This script is a java processing code with many variables, generating a new permutation with every click. The script is written in a manner that the very same piece can't be created twice; each conception is unique.
            <br />
            <br />
            A complimentary file is created to preserve the sanctity of the particular randomly generated artwork, where all the (x,y) inputs generating that piece are stored. These inputs can be re-run and will continue to yield the same result every time.
            <br />
            <br />
            You get a randomly selected high resolution (3000x3000px) image from the whole collection when you mint a noise. In addition, you can also have the code that generated it, on request.
            Having this code, you have a million points that created your very own noise.
          </p>

          <div className='division-div'></div>

          <h4 className='subheading'>How to Mint</h4>
          <p>
            If you resonate with the language of artworks presented by Project Noise, you can mint a unique piece for yourself, here. The minting date and time will be specified on the landing page itself. Tokens will be available on a first-come-first-serve basis, and each wallet can mint one piece per transaction.
          </p><br />
          <p>
            To mint, you will first need a Solana compatible wallet like phantom, solflare, etc. If not already installed, you can find the instructions here. Then, you will need some Solana in the wallet which can be purchased from a decentralized exchange or any of the famous exchanges like Coinbase, Binance, FTX, and more.
          </p><br />
          <p>
            With the wallet installed and some SOL in place, visit the landing page and connect your wallet via the "connect wallet" option on the top right corner of your screen.
          </p><br />
          <p>
            Once the wallet is connected, click on the "mint" button and a window should pop up asking to approve the transaction. Click on approve and you are all set. The artwork should display in the collectibles tab of your wallet.
          </p>

          <div className='division-div'></div>

          <h4 className='subheading'>More Info</h4>
          <p>
            For more information please reach out to us on Twitter or join the conversation in Discord.
          </p>
        </Col>
        <Col></Col>
        <Col lg={3}></Col>
      </Row>
    </div >
  );
};

export default LearnPage;